<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Printexc (ocaml.Printexc)</title><link rel="stylesheet" href="../../odoc.css"/><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><script src="../../highlight.pack.js"></script><script>hljs.initHighlightingOnLoad();</script></head><body><header><nav><a href="../index.html">Up</a> â€“ package <a href="../index.html">ocaml</a></nav><h1>Module <code>Printexc</code></h1><p>Facilities for printing exceptions and inspecting current call stack.</p></header><dl><dt id="val-to_string"><a href="#val-to_string" class="anchor"></a><code><span class="keyword">val </span>to_string : exn <span>&#8209;&gt;</span> string</code></dt><dd><p><code>Printexc.to_string e</code> returns a string representation of the exception <code>e</code>.</p></dd></dl><dl><dt id="val-print"><a href="#val-print" class="anchor"></a><code><span class="keyword">val </span>print : (<span class="type-var">'a</span> <span>&#8209;&gt;</span> <span class="type-var">'b</span>) <span>&#8209;&gt;</span> <span class="type-var">'a</span> <span>&#8209;&gt;</span> <span class="type-var">'b</span></code></dt><dd><p><code>Printexc.print fn x</code> applies <code>fn</code> to <code>x</code> and returns the result. If the evaluation of <code>fn x</code> raises any exception, the name of the exception is printed on standard error output, and the exception is raised again. The typical use is to catch and report exceptions that escape a function application.</p></dd></dl><dl><dt id="val-catch"><a href="#val-catch" class="anchor"></a><code><span class="keyword">val </span>catch : (<span class="type-var">'a</span> <span>&#8209;&gt;</span> <span class="type-var">'b</span>) <span>&#8209;&gt;</span> <span class="type-var">'a</span> <span>&#8209;&gt;</span> <span class="type-var">'b</span></code></dt><dd><p><code>Printexc.catch fn x</code> is similar to <a href="index.html#val-print"><code>Printexc.print</code></a>, but aborts the program with exit code 2 after printing the uncaught exception. This function is deprecated: the runtime system is now able to print uncaught exceptions as precisely as <code>Printexc.catch</code> does. Moreover, calling <code>Printexc.catch</code> makes it harder to track the location of the exception using the debugger or the stack backtrace facility. So, do not use <code>Printexc.catch</code> in new code.</p></dd></dl><dl><dt id="val-print_backtrace"><a href="#val-print_backtrace" class="anchor"></a><code><span class="keyword">val </span>print_backtrace : <a href="../Pervasives/index.html#type-out_channel">Pervasives.out_channel</a> <span>&#8209;&gt;</span> unit</code></dt><dd><p><code>Printexc.print_backtrace oc</code> prints an exception backtrace on the output channel <code>oc</code>. The backtrace lists the program locations where the most-recently raised exception was raised and where it was propagated through function calls.</p><p>If the call is not inside an exception handler, the returned backtrace is unspecified. If the call is after some exception-catching code (before in the handler, or in a when-guard during the matching of the exception handler), the backtrace may correspond to a later exception than the handled one.</p><dl><dt>since</dt><dd>3.11.0</dd></dl></dd></dl><dl><dt id="val-get_backtrace"><a href="#val-get_backtrace" class="anchor"></a><code><span class="keyword">val </span>get_backtrace : unit <span>&#8209;&gt;</span> string</code></dt><dd><p><code>Printexc.get_backtrace ()</code> returns a string containing the same exception backtrace that <code>Printexc.print_backtrace</code> would print. Same restriction usage than <a href="index.html#val-print_backtrace"><code>print_backtrace</code></a>.</p><dl><dt>since</dt><dd>3.11.0</dd></dl></dd></dl><dl><dt id="val-record_backtrace"><a href="#val-record_backtrace" class="anchor"></a><code><span class="keyword">val </span>record_backtrace : bool <span>&#8209;&gt;</span> unit</code></dt><dd><p><code>Printexc.record_backtrace b</code> turns recording of exception backtraces on (if <code>b = true</code>) or off (if <code>b = false</code>). Initially, backtraces are not recorded, unless the <code>b</code> flag is given to the program through the <code>OCAMLRUNPARAM</code> variable.</p><dl><dt>since</dt><dd>3.11.0</dd></dl></dd></dl><dl><dt id="val-backtrace_status"><a href="#val-backtrace_status" class="anchor"></a><code><span class="keyword">val </span>backtrace_status : unit <span>&#8209;&gt;</span> bool</code></dt><dd><p><code>Printexc.backtrace_status()</code> returns <code>true</code> if exception backtraces are currently recorded, <code>false</code> if not.</p><dl><dt>since</dt><dd>3.11.0</dd></dl></dd></dl><dl><dt id="val-register_printer"><a href="#val-register_printer" class="anchor"></a><code><span class="keyword">val </span>register_printer : (exn <span>&#8209;&gt;</span> string option) <span>&#8209;&gt;</span> unit</code></dt><dd><p><code>Printexc.register_printer fn</code> registers <code>fn</code> as an exception printer. The printer should return <code>None</code> or raise an exception if it does not know how to convert the passed exception, and <code>Some
    s</code> with <code>s</code> the resulting string if it can convert the passed exception. Exceptions raised by the printer are ignored.</p><p>When converting an exception into a string, the printers will be invoked in the reverse order of their registrations, until a printer returns a <code>Some s</code> value (if no such printer exists, the runtime will use a generic printer).</p><p>When using this mechanism, one should be aware that an exception backtrace is attached to the thread that saw it raised, rather than to the exception itself. Practically, it means that the code related to <code>fn</code> should not use the backtrace if it has itself raised an exception before.</p><dl><dt>since</dt><dd>3.11.2</dd></dl></dd></dl></body></html>